[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.20.2"
  NPM_VERSION = "8"
  NPM_FLAGS = "--version"
  # Disable pnpm
  NPM_LOCK = "package-lock.json"
  USE_NPM = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
