[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.20.2"
  NPM_VERSION = "8.19.4"
  NPM_FLAGS = "--legacy-peer-deps --no-fund --no-audit --prefer-offline"
  CI = "false"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NPM_CONFIG_PREFER_OFFLINE = "true"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_PRODUCTION = "false"

[build.processing]
  skip_processing = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "build"
  targetPort = 3000
